using System.Net;
using System.Text;
using System.Text.Json;
using AIHappey.Core.AI;
using AIHappey.Core.Contracts;
using AIHappey.Core.Providers.Jules;
using AIHappey.Tests.TestInfrastructure;
using AIHappey.Unified.Models;
using Microsoft.Extensions.Caching.Memory;
using ModelContextProtocol.Protocol;

namespace AIHappey.Tests.Jules;

public class JulesProviderUnifiedTests
{
    [Fact]
    public async Task ListModels_returns_source_shortcut_models_from_sources_api()
    {
        var provider = CreateProvider(request =>
        {
            Assert.Equal(HttpMethod.Get, request.Method);
            Assert.Equal("/v1alpha/sources", request.RequestUri?.AbsolutePath);
            Assert.Equal("test-api-key", TryGetSingleHeaderValue(request, "X-Goog-Api-Key"));

            return JsonResponse(new
            {
                sources = new[]
                {
                    new
                    {
                        name = "sources/github/acme/api",
                        id = "github/acme/api",
                        githubRepo = new
                        {
                            owner = "acme",
                            repo = "api"
                        }
                    }
                }
            });
        });

        var models = (await provider.ListModels()).ToList();

        var shortcut = models.Single(model => model.Id == "jules/sources/github/acme/api");
        Assert.Equal("acme/api", shortcut.Name);
        Assert.Contains("shortcut", shortcut.Tags ?? []);
        Assert.Contains("source:sources/github/acme/api", shortcut.Tags ?? []);
    }

    [Fact]
    public async Task ExecuteUnifiedAsync_creates_session_from_source_shortcut_model_and_returns_provider_tool_call()
    {
        string? createBody = null;

        var provider = CreateProvider(request =>
        {
            if (request.Method == HttpMethod.Post && request.RequestUri?.AbsolutePath == "/v1alpha/sessions")
            {
                createBody = request.Content!.ReadAsStringAsync().GetAwaiter().GetResult();
                return JsonResponse(new
                {
                    id = "sess_123",
                    name = "sessions/sess_123",
                    state = "IN_PROGRESS",
                    sourceContext = new
                    {
                        source = "sources/github/acme/api",
                        githubRepoContext = new { startingBranch = "main" }
                    }
                });
            }

            if (request.Method == HttpMethod.Get && request.RequestUri?.AbsolutePath == "/v1alpha/sessions/sess_123")
            {
                return JsonResponse(new
                {
                    id = "sess_123",
                    name = "sessions/sess_123",
                    state = "COMPLETED",
                    url = "https://jules.google.com/sessions/sess_123",
                    sourceContext = new
                    {
                        source = "sources/github/acme/api",
                        githubRepoContext = new { startingBranch = "main" }
                    },
                    outputs = new[]
                    {
                        new
                        {
                            pullRequest = new
                            {
                                url = "https://github.com/acme/api/pull/1",
                                title = "feat: add api",
                                description = "Generated by Jules"
                            }
                        }
                    }
                });
            }

            if (request.Method == HttpMethod.Get && request.RequestUri?.AbsolutePath == "/v1alpha/sessions/sess_123/activities")
            {
                return JsonResponse(new
                {
                    activities = new object[]
                    {
                        new
                        {
                            id = "act_plan",
                            createTime = "2026-05-01T10:00:00Z",
                            planGenerated = new
                            {
                                plan = new
                                {
                                    id = "plan_123",
                                    steps = new[]
                                    {
                                        new { id = "step_1", index = 0, title = "Inspect repo" },
                                        new { id = "step_2", index = 1, title = "Implement feature" }
                                    }
                                }
                            }
                        },
                        new
                        {
                            id = "act_progress",
                            createTime = "2026-05-01T10:00:01Z",
                            progressUpdated = new
                            {
                                title = "Implemented feature",
                                description = "Updated backend mapping."
                            }
                        },
                        new
                        {
                            id = "act_done",
                            createTime = "2026-05-01T10:00:02Z",
                            sessionCompleted = new { }
                        }
                    }
                });
            }

            return NotFound(request);
        });

        var response = await provider.ExecuteUnifiedAsync(new AIRequest
        {
            ProviderId = "jules",
            Model = "jules/sources/github/acme/api",
            Metadata = new Dictionary<string, object?>
            {
                ["jules"] = new
                {
                    startingBranch = "main",
                    title = "API work"
                }
            },
            Input = new AIInput
            {
                Items =
                [
                    new AIInputItem
                    {
                        Role = "user",
                        Content =
                        [
                            new AITextContentPart { Type = "text", Text = "Implement the new mapping." }
                        ]
                    }
                ]
            }
        });

        Assert.NotNull(createBody);
        Assert.Contains("\"source\":\"sources/github/acme/api\"", createBody, StringComparison.Ordinal);
        Assert.Contains("\"startingBranch\":\"main\"", createBody, StringComparison.Ordinal);

        Assert.Equal("completed", response.Status);
        Assert.Equal("jules/sources/github/acme/api", response.Model);

        var messageItem = Assert.Single(response.Output!.Items!.Where(item => item.Type == "message"));
        var sessionTool = Assert.IsType<AIToolCallContentPart>(messageItem.Content!.First());
        Assert.True(sessionTool.ProviderExecuted);
        Assert.Equal("create_session", sessionTool.ToolName);

        var sessionToolOutput = JsonSerializer.SerializeToElement(sessionTool.Output, JsonSerializerOptions.Web);
        var structuredContent = sessionToolOutput.GetProperty("structuredContent");
        Assert.Equal("sess_123", structuredContent.GetProperty("sessionId").GetString());

        Assert.Contains(messageItem.Content!, part => part is AIReasoningContentPart reasoning && reasoning.Text!.Contains("Inspect repo", StringComparison.Ordinal));
        Assert.Contains(messageItem.Content!, part => part is AITextContentPart text && text.Text.Contains("Implemented feature", StringComparison.Ordinal));
        Assert.Contains(response.Output.Items!, item => item.Type == "source-url" && Equals(item.Metadata!["source.url"], "https://github.com/acme/api/pull/1"));
    }

    [Fact]
    public async Task ExecuteUnifiedAsync_reuses_session_from_prior_provider_tool_output()
    {
        var createSessionCalls = 0;
        string? sendMessageBody = null;

        var provider = CreateProvider(request =>
        {
            if (request.Method == HttpMethod.Post && request.RequestUri?.AbsolutePath == "/v1alpha/sessions")
            {
                createSessionCalls++;
                return JsonResponse(new { id = "should-not-be-used" });
            }

            if (request.Method == HttpMethod.Post && request.RequestUri?.AbsolutePath == "/v1alpha/sessions/sess_existing:sendMessage")
            {
                sendMessageBody = request.Content!.ReadAsStringAsync().GetAwaiter().GetResult();
                return JsonResponse(new { });
            }

            if (request.Method == HttpMethod.Get && request.RequestUri?.AbsolutePath == "/v1alpha/sessions/sess_existing")
            {
                return JsonResponse(new
                {
                    id = "sess_existing",
                    name = "sessions/sess_existing",
                    state = "COMPLETED",
                    sourceContext = new
                    {
                        source = "sources/github/acme/api",
                        githubRepoContext = new { startingBranch = "main" }
                    }
                });
            }

            if (request.Method == HttpMethod.Get && request.RequestUri?.AbsolutePath == "/v1alpha/sessions/sess_existing/activities")
            {
                return JsonResponse(new
                {
                    activities = new object[]
                    {
                        new
                        {
                            id = "act_reply",
                            createTime = "2026-05-01T10:01:00Z",
                            agentMessaged = new
                            {
                                agentMessage = "Reused existing Jules session"
                            }
                        }
                    }
                });
            }

            return NotFound(request);
        });

        var response = await provider.ExecuteUnifiedAsync(new AIRequest
        {
            ProviderId = "jules",
            Model = "jules/sources/github/acme/api",
            Input = new AIInput
            {
                Items =
                [
                    new AIInputItem
                    {
                        Role = "assistant",
                        Content =
                        [
                            new AIToolCallContentPart
                            {
                                Type = "tool-call",
                                ToolCallId = "jules-create-session-sess_existing",
                                ToolName = "create_session",
                                ProviderExecuted = true,
                                State = "output-available",
                                Output = new CallToolResult
                                {
                                    Content = [],
                                    StructuredContent = JsonSerializer.SerializeToElement(new
                                    {
                                        sessionId = "sess_existing",
                                        session_id = "sess_existing"
                                    }, JsonSerializerOptions.Web)
                                }
                            }
                        ]
                    },
                    new AIInputItem
                    {
                        Role = "user",
                        Content =
                        [
                            new AITextContentPart { Type = "text", Text = "Please continue." }
                        ]
                    }
                ]
            }
        });

        Assert.Equal(0, createSessionCalls);
        Assert.NotNull(sendMessageBody);
        Assert.Contains("Please continue.", sendMessageBody, StringComparison.Ordinal);

        var messageItem = Assert.Single(response.Output!.Items!.Where(item => item.Type == "message"));
        var textPart = Assert.IsType<AITextContentPart>(Assert.Single(messageItem.Content!));
        Assert.Equal("Reused existing Jules session", textPart.Text);
    }

    [Fact]
    public async Task StreamUnifiedAsync_emits_session_tool_reasoning_text_and_finish_events()
    {
        var getSessionCalls = 0;

        var provider = CreateProvider(request =>
        {
            if (request.Method == HttpMethod.Post && request.RequestUri?.AbsolutePath == "/v1alpha/sessions")
            {
                return JsonResponse(new
                {
                    id = "sess_stream",
                    name = "sessions/sess_stream",
                    state = "IN_PROGRESS",
                    sourceContext = new
                    {
                        source = "sources/github/acme/api",
                        githubRepoContext = new { startingBranch = "main" }
                    }
                });
            }

            if (request.Method == HttpMethod.Get && request.RequestUri?.AbsolutePath == "/v1alpha/sessions/sess_stream")
            {
                getSessionCalls++;
                return JsonResponse(new
                {
                    id = "sess_stream",
                    name = "sessions/sess_stream",
                    state = getSessionCalls == 1 ? "IN_PROGRESS" : "COMPLETED",
                    url = "https://jules.google.com/sessions/sess_stream",
                    sourceContext = new
                    {
                        source = "sources/github/acme/api",
                        githubRepoContext = new { startingBranch = "main" }
                    }
                });
            }

            if (request.Method == HttpMethod.Get && request.RequestUri?.AbsolutePath == "/v1alpha/sessions/sess_stream/activities")
            {
                return JsonResponse(new
                {
                    activities = new object[]
                    {
                        new
                        {
                            id = "act_plan_stream",
                            createTime = "2026-05-01T10:02:00Z",
                            planGenerated = new
                            {
                                plan = new
                                {
                                    id = "plan_stream",
                                    steps = new[]
                                    {
                                        new { id = "step_1", index = 0, title = "Plan work" }
                                    }
                                }
                            }
                        },
                        new
                        {
                            id = "act_progress_stream",
                            createTime = "2026-05-01T10:02:01Z",
                            progressUpdated = new
                            {
                                title = "Finished implementation"
                            }
                        }
                    }
                });
            }

            return NotFound(request);
        });

        var events = await FixtureAssertions.CollectAsync(provider.StreamUnifiedAsync(new AIRequest
        {
            ProviderId = "jules",
            Model = "jules/sources/github/acme/api",
            Metadata = new Dictionary<string, object?>
            {
                ["jules"] = new
                {
                    startingBranch = "main",
                    poll_seconds = 0,
                    poll_max_attempts = 3
                }
            },
            Input = new AIInput
            {
                Items =
                [
                    new AIInputItem
                    {
                        Role = "user",
                        Content =
                        [
                            new AITextContentPart { Type = "text", Text = "Do the work." }
                        ]
                    }
                ]
            }
        }));

        Assert.Equal(
            new[]
            {
                "tool-input-available",
                "tool-output-available",
                "reasoning-start",
                "reasoning-delta",
                "reasoning-end",
                "text-start",
                "text-delta",
                "source-url",
                "text-end",
                "finish"
            },
            events.Select(evt => evt.Event.Type));
    }

    private static JulesProvider CreateProvider(Func<HttpRequestMessage, HttpResponseMessage> responder)
        => new(
            new StaticApiKeyResolver(),
            new AsyncCacheHelper(new MemoryCache(new MemoryCacheOptions())),
            new StaticHttpClientFactory(new HttpClient(new StaticResponseHttpMessageHandler(responder))
            {
                BaseAddress = new Uri("https://jules.googleapis.com/v1alpha/")
            }));

    private static HttpResponseMessage JsonResponse(object payload)
        => new(HttpStatusCode.OK)
        {
            Content = new StringContent(
                JsonSerializer.Serialize(payload, JsonSerializerOptions.Web),
                Encoding.UTF8,
                "application/json")
        };

    private static HttpResponseMessage NotFound(HttpRequestMessage request)
        => new(HttpStatusCode.NotFound)
        {
            Content = new StringContent($"Unhandled request: {request.Method} {request.RequestUri}")
        };

    private static string? TryGetSingleHeaderValue(HttpRequestMessage request, string headerName)
        => request.Headers.TryGetValues(headerName, out var values)
            ? values.SingleOrDefault()
            : null;

    private sealed class StaticApiKeyResolver : IApiKeyResolver
    {
        public string? Resolve(string provider)
            => "test-api-key";
    }

    private sealed class StaticHttpClientFactory(HttpClient httpClient) : IHttpClientFactory
    {
        public HttpClient CreateClient(string name)
            => httpClient;
    }

    private sealed class StaticResponseHttpMessageHandler(Func<HttpRequestMessage, HttpResponseMessage> responder) : HttpMessageHandler
    {
        protected override Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
        {
            var response = responder(request);
            response.RequestMessage = request;
            return Task.FromResult(response);
        }
    }
}
