using AIHappey.Core.AI;
using AIHappey.Core.Models;

namespace AIHappey.Core.Providers.NLPCloud;

public partial class NLPCloudProvider
{
   public async Task<IEnumerable<Model>> ListModels(CancellationToken cancellationToken = default)
   {
      if (string.IsNullOrWhiteSpace(_keyResolver.Resolve(GetIdentifier())))
         return await Task.FromResult<IEnumerable<Model>>([]);


      ApplyAuthHeader();

      return [.. NLPCloudLanguageModels];
   }

   public IReadOnlyList<Model> NLPCloudLanguageModels =>
   [
       new() { Id = "gpt-oss-120b".ToModelId(GetIdentifier()),
            Name = "gpt-oss-120b",
            Type = "language",
            OwnedBy = nameof(NLPCloud) },
         new() { Id = "finetuned-llama-3-70b".ToModelId(GetIdentifier()),
            Name = "finetuned-llama-3-70b",
            Type = "language",
            OwnedBy = nameof(NLPCloud) },
         new() { Id = "chatdolphin".ToModelId(GetIdentifier()),
            Name = "chatdolphin",
            Type = "language",
            OwnedBy = nameof(NLPCloud) },
         new() { Id = "dolphin-yi-34b".ToModelId(GetIdentifier()),
            Name = "dolphin-yi-34b",
            Type = "language",
            OwnedBy = nameof(NLPCloud) },
          new() { Id = "dolphin-mixtral-8x7b".ToModelId(GetIdentifier()),
            Name = "dolphin-mixtral-8x7b",
            Type = "language",
            OwnedBy = nameof(NLPCloud) },
         new() { Id = "llama-3-1-405b".ToModelId(GetIdentifier()),
            Name = "llama-3-1-405b",
            Type = "language",
            OwnedBy =  nameof(NLPCloud)  },
        new() { Id = "gpt-oss-120b/paraphrasing".ToModelId(GetIdentifier()),
            Name = "gpt-oss-120b Paraphrasing",
            Description = "Rephrases your original text so the words are different but the meaning remains the same.",
            Type = "language",
            OwnedBy = nameof(NLPCloud) },
        new() { Id = "finetuned-llama-3-70b/paraphrasing".ToModelId(GetIdentifier()),
            Name = "finetuned-llama-3-70b Paraphrasing",
            Description = "Rephrases your original text so the words are different but the meaning remains the same.",
            Type = "language",
            OwnedBy = nameof(NLPCloud) },
        new() { Id = "llama-3-1-405b/paraphrasing".ToModelId(GetIdentifier()),
            Name = "llama-3-1-405b Paraphrasing",
            Description = "Rephrases your original text so the words are different but the meaning remains the same.",
            Type = "language",
            OwnedBy =  nameof(NLPCloud)  },

        new() { Id = "gpt-oss-120b/summarization".ToModelId(GetIdentifier()),
            Name = "gpt-oss-120b Summarization",
            Description = "Performs text summarization in many languages. These are 'abstractive' summarizations, which means that some sentences are directly taken from the input text, but also that new sentences might be generated.",
            Type = "language",
            OwnedBy = nameof(NLPCloud) },
         new() { Id = "finetuned-llama-3-70b/summarization".ToModelId(GetIdentifier()),
            Name = "finetuned-llama-3-70b Summarization",
            Description = "Performs text summarization in many languages. These are 'abstractive' summarizations, which means that some sentences are directly taken from the input text, but also that new sentences might be generated.",
            Type = "language",
            OwnedBy = nameof(NLPCloud) },
         new() { Id = "chatdolphin/summarization".ToModelId(GetIdentifier()),
            Name = "chatdolphin Summarization",
            Description = "Performs text summarization in many languages. These are 'abstractive' summarizations, which means that some sentences are directly taken from the input text, but also that new sentences might be generated.",
            Type = "language",
            OwnedBy = nameof(NLPCloud) },
         new() { Id = "dolphin-yi-34b/summarization".ToModelId(GetIdentifier()),
            Name = "dolphin-yi-34b Summarization",
            Description = "Performs text summarization in many languages. These are 'abstractive' summarizations, which means that some sentences are directly taken from the input text, but also that new sentences might be generated.",
            Type = "language",
            OwnedBy = nameof(NLPCloud) },
          new() { Id = "dolphin-mixtral-8x7b/summarization".ToModelId(GetIdentifier()),
            Name = "dolphin-mixtral-8x7b Summarization",
            Description = "Performs text summarization in many languages. These are 'abstractive' summarizations, which means that some sentences are directly taken from the input text, but also that new sentences might be generated.",
            Type = "language",
            OwnedBy = nameof(NLPCloud) },
         new() { Id = "llama-3-1-405b/summarization".ToModelId(GetIdentifier()),
            Name = "llama-3-1-405b Summarization",
            Description = "Performs text summarization in many languages. These are 'abstractive' summarizations, which means that some sentences are directly taken from the input text, but also that new sentences might be generated.",
            Type = "language",
            OwnedBy =  nameof(NLPCloud)  },

         new() { Id = "bart-large-cnn/summarization".ToModelId(GetIdentifier()),
            Name = "bart-large-cnn Summarization",
            Description = "Performs text summarization in many languages. These are 'abstractive' summarizations, which means that some sentences are directly taken from the input text, but also that new sentences might be generated.",
            Type = "language",
            OwnedBy =  nameof(NLPCloud)  },

         new() { Id = "t5-base-en-generate-headline/summarization".ToModelId(GetIdentifier()),
            Name = "t5-base-en-generate-headline Summarization",
            Description = "Performs text summarization in many languages. These are 'abstractive' summarizations, which means that some sentences are directly taken from the input text, but also that new sentences might be generated.",
            Type = "language",
            OwnedBy =  nameof(NLPCloud)  },




        new() { Id = "gpt-oss-120b/code-generation".ToModelId(GetIdentifier()),
            Name = "gpt-oss-120b Code Generation",
            Description = "Takes a short instruction and generates a source code out of it in any programming language. Make sure to mention the language you want to use in your instruction.",
            Type = "language",
            OwnedBy = nameof(NLPCloud) },
         new() { Id = "finetuned-llama-3-70b/code-generation".ToModelId(GetIdentifier()),
            Name = "finetuned-llama-3-70b Code Generation",
            Description = "Takes a short instruction and generates a source code out of it in any programming language. Make sure to mention the language you want to use in your instruction.",
            Type = "language",
            OwnedBy = nameof(NLPCloud) },
         new() { Id = "chatdolphin/code-generation".ToModelId(GetIdentifier()),
            Name = "chatdolphin Code Generation",
            Description = "Takes a short instruction and generates a source code out of it in any programming language. Make sure to mention the language you want to use in your instruction.",
            Type = "language",
            OwnedBy = nameof(NLPCloud) },
         new() { Id = "dolphin-yi-34b/code-generation".ToModelId(GetIdentifier()),
            Name = "dolphin-yi-34b Code Generation",
            Description = "Takes a short instruction and generates a source code out of it in any programming language. Make sure to mention the language you want to use in your instruction.",
            Type = "language",
            OwnedBy = nameof(NLPCloud) },
          new() { Id = "dolphin-mixtral-8x7b/code-generation".ToModelId(GetIdentifier()),
            Name = "dolphin-mixtral-8x7b Code Generation",
            Description = "Takes a short instruction and generates a source code out of it in any programming language. Make sure to mention the language you want to use in your instruction.",
            Type = "language",
            OwnedBy = nameof(NLPCloud) },
         new() { Id = "llama-3-1-405b/code-generation".ToModelId(GetIdentifier()),
            Name = "llama-3-1-405b Code Generation",
            Description = "Takes a short instruction and generates a source code out of it in any programming language. Make sure to mention the language you want to use in your instruction.",
            Type = "language",
            OwnedBy =  nameof(NLPCloud)  },



        new() { Id = "gpt-oss-120b/intent-classification".ToModelId(GetIdentifier()),
            Name = "gpt-oss-120b Intent Classification",
            Description = "Tries to detect what is the main intent in the text.",
            Type = "language",
            OwnedBy = nameof(NLPCloud) },
         new() { Id = "finetuned-llama-3-70b/intent-classification".ToModelId(GetIdentifier()),
            Name = "finetuned-llama-3-70b Intent Classification",
            Description = "Tries to detect what is the main intent in the text.",
            Type = "language",
            OwnedBy = nameof(NLPCloud) },
         new() { Id = "chatdolphin/intent-classification".ToModelId(GetIdentifier()),
            Name = "chatdolphin Intent Classification",
            Description = "Tries to detect what is the main intent in the text.",
            Type = "language",
            OwnedBy = nameof(NLPCloud) },
         new() { Id = "dolphin-yi-34b/intent-classification".ToModelId(GetIdentifier()),
            Name = "dolphin-yi-34b Intent Classification",
            Description = "Tries to detect what is the main intent in the text.",
            Type = "language",
            OwnedBy = nameof(NLPCloud) },
          new() { Id = "dolphin-mixtral-8x7b/intent-classification".ToModelId(GetIdentifier()),
            Name = "dolphin-mixtral-8x7b Intent Classification",
            Description = "Tries to detect what is the main intent in the text.",
            Type = "language",
            OwnedBy = nameof(NLPCloud) },
         new() { Id = "llama-3-1-405b/intent-classification".ToModelId(GetIdentifier()),
            Name = "llama-3-1-405b Intent Classification",
            Description = "Tries to detect what is the main intent in the text.",
            Type = "language",
            OwnedBy =  nameof(NLPCloud)  },




        new() { Id = "gpt-oss-120b/gs-correction".ToModelId(GetIdentifier()),
            Name = "gpt-oss-120b Grammar and Spelling Correction",
            Description = "Performs grammar and spelling correction. The model takes your input and returns the same thing, but without any mistake.",
            Type = "language",
            OwnedBy = nameof(NLPCloud) },
         new() { Id = "finetuned-llama-3-70b/gs-correction".ToModelId(GetIdentifier()),
            Name = "finetuned-llama-3-70b Grammar and Spelling Correction",
            Description = "Performs grammar and spelling correction. The model takes your input and returns the same thing, but without any mistake.",
            Type = "language",
            OwnedBy = nameof(NLPCloud) },
         new() { Id = "chatdolphin/gs-correction".ToModelId(GetIdentifier()),
            Name = "chatdolphin Grammar and Spelling Correction",
            Description = "Performs grammar and spelling correction. The model takes your input and returns the same thing, but without any mistake.",
            Type = "language",
            OwnedBy = nameof(NLPCloud) },
         new() { Id = "dolphin-yi-34b/gs-correction".ToModelId(GetIdentifier()),
            Name = "dolphin-yi-34b Grammar and Spelling Correction",
            Description = "Performs grammar and spelling correction. The model takes your input and returns the same thing, but without any mistake.",
            Type = "language",
            OwnedBy = nameof(NLPCloud) },
          new() { Id = "dolphin-mixtral-8x7b/gs-correction".ToModelId(GetIdentifier()),
            Name = "dolphin-mixtral-8x7b Grammar and Spelling Correction",
            Description = "Performs grammar and spelling correction. The model takes your input and returns the same thing, but without any mistake.",
            Type = "language",
            OwnedBy = nameof(NLPCloud) },
         new() { Id = "llama-3-1-405b/gs-correction".ToModelId(GetIdentifier()),
            Name = "llama-3-1-405b Grammar and Spelling Correction",
            Description = "Performs grammar and spelling correction. The model takes your input and returns the same thing, but without any mistake.",
            Type = "language",
            OwnedBy =  nameof(NLPCloud)  },



        new() { Id = "gpt-oss-120b/kw-kp-extraction".ToModelId(GetIdentifier()),
            Name = "gpt-oss-120b Keywords and Keyphrases Extraction",
            Description = "Performs keywords and keyphrases extraction. The model extracts the main ideas from your text. These ideas can be keywords or a couple of keywords (also known as keyphrases).",
            Type = "language",
            OwnedBy = nameof(NLPCloud) },
         new() { Id = "finetuned-llama-3-70b/kw-kp-extraction".ToModelId(GetIdentifier()),
            Name = "finetuned-llama-3-70b Keywords and Keyphrases Extraction",
            Description = "Performs keywords and keyphrases extraction. The model extracts the main ideas from your text. These ideas can be keywords or a couple of keywords (also known as keyphrases).",
            Type = "language",
            OwnedBy = nameof(NLPCloud) },

        new() { Id = "llama-3-1-405b/kw-kp-extraction".ToModelId(GetIdentifier()),
            Name = "llama-3-1-405b Keywords and Keyphrases Extraction",
            Description = "Performs keywords and keyphrases extraction. The model extracts the main ideas from your text. These ideas can be keywords or a couple of keywords (also known as keyphrases).",
            Type = "language",
            OwnedBy =  nameof(NLPCloud)  },




        new() { Id = "speech-t5".ToModelId(GetIdentifier()),
            Name = "speech-t5",
            Type = "speech",
            OwnedBy =  nameof(NLPCloud)  },

         new() { Id = "whisper/asr".ToModelId(GetIdentifier()),
            Name = "whisper",
            Type = "transcription",
            OwnedBy =  nameof(NLPCloud)  },

        ..NLLBTranslateModels
   ];


   public IReadOnlyList<Model> NLLBTranslateModels =>
   [.. NllbLanguages
        .Select(kv => new Model
        {
            Id = $"nllb-200-3-3b/translate-to/{kv.Key}".ToModelId(GetIdentifier()),
            Name = $"nllb-200-3-3b Translate to {kv.Value}",
            Description = "Send a sentence, and the model will return a translation.",
            Type = "language",
            OwnedBy = nameof(NLPCloud)
        })];

   private static readonly Dictionary<string, string> NllbLanguages = new()
   {
      ["ace_Arab"] = "Acehnese (Arabic script)",
      ["ace_Latn"] = "Acehnese (Latin script)",
      ["acm_Arab"] = "Mesopotamian Arabic",
      ["acq_Arab"] = "Ta’izzi-Adeni Arabic",
      ["aeb_Arab"] = "Tunisian Arabic",
      ["afr_Latn"] = "Afrikaans",
      ["ajp_Arab"] = "South Levantine Arabic",
      ["aka_Latn"] = "Akan",
      ["amh_Ethi"] = "Amharic",
      ["apc_Arab"] = "North Levantine Arabic",
      ["arb_Arab"] = "Modern Standard Arabic",
      ["arb_Latn"] = "Modern Standard Arabic (Romanized)",
      ["ars_Arab"] = "Najdi Arabic",
      ["ary_Arab"] = "Moroccan Arabic",
      ["arz_Arab"] = "Egyptian Arabic",
      ["asm_Beng"] = "Assamese",
      ["ast_Latn"] = "Asturian",
      ["awa_Deva"] = "Awadhi",
      ["ayr_Latn"] = "Central Aymara",
      ["azb_Arab"] = "South Azerbaijani",
      ["azj_Latn"] = "North Azerbaijani",
      ["bak_Cyrl"] = "Bashkir",
      ["bam_Latn"] = "Bambara",
      ["ban_Latn"] = "Balinese",
      ["bel_Cyrl"] = "Belarusian",
      ["bem_Latn"] = "Bemba",
      ["ben_Beng"] = "Bengali",
      ["bho_Deva"] = "Bhojpuri",
      ["bjn_Arab"] = "Banjar (Arabic script)",
      ["bjn_Latn"] = "Banjar (Latin script)",
      ["bod_Tibt"] = "Standard Tibetan",
      ["bos_Latn"] = "Bosnian",
      ["bug_Latn"] = "Buginese",
      ["bul_Cyrl"] = "Bulgarian",
      ["cat_Latn"] = "Catalan",
      ["ceb_Latn"] = "Cebuano",
      ["ces_Latn"] = "Czech",
      ["cjk_Latn"] = "Chokwe",
      ["ckb_Arab"] = "Central Kurdish",
      ["crh_Latn"] = "Crimean Tatar",
      ["cym_Latn"] = "Welsh",
      ["dan_Latn"] = "Danish",
      ["deu_Latn"] = "German",
      ["dik_Latn"] = "Southwestern Dinka",
      ["dyu_Latn"] = "Dyula",
      ["dzo_Tibt"] = "Dzongkha",
      ["ell_Grek"] = "Greek",
      ["eng_Latn"] = "English",
      ["epo_Latn"] = "Esperanto",
      ["est_Latn"] = "Estonian",
      ["eus_Latn"] = "Basque",
      ["ewe_Latn"] = "Ewe",
      ["fao_Latn"] = "Faroese",
      ["fij_Latn"] = "Fijian",
      ["fin_Latn"] = "Finnish",
      ["fon_Latn"] = "Fon",
      ["fra_Latn"] = "French",
      ["fur_Latn"] = "Friulian",
      ["fuv_Latn"] = "Nigerian Fulfulde",
      ["gla_Latn"] = "Scottish Gaelic",
      ["gle_Latn"] = "Irish",
      ["glg_Latn"] = "Galician",
      ["grn_Latn"] = "Guarani",
      ["guj_Gujr"] = "Gujarati",
      ["hat_Latn"] = "Haitian Creole",
      ["hau_Latn"] = "Hausa",
      ["heb_Hebr"] = "Hebrew",
      ["hin_Deva"] = "Hindi",
      ["hne_Deva"] = "Chhattisgarhi",
      ["hrv_Latn"] = "Croatian",
      ["hun_Latn"] = "Hungarian",
      ["hye_Armn"] = "Armenian",
      ["ibo_Latn"] = "Igbo",
      ["ilo_Latn"] = "Ilocano",
      ["ind_Latn"] = "Indonesian",
      ["isl_Latn"] = "Icelandic",
      ["ita_Latn"] = "Italian",
      ["jav_Latn"] = "Javanese",
      ["jpn_Jpan"] = "Japanese",
      ["kab_Latn"] = "Kabyle",
      ["kac_Latn"] = "Jingpho",
      ["kam_Latn"] = "Kamba",
      ["kan_Knda"] = "Kannada",
      ["kas_Arab"] = "Kashmiri (Arabic script)",
      ["kas_Deva"] = "Kashmiri (Devanagari script)",
      ["kat_Geor"] = "Georgian",
      ["knc_Arab"] = "Central Kanuri (Arabic script)",
      ["knc_Latn"] = "Central Kanuri (Latin script)",
      ["kaz_Cyrl"] = "Kazakh",
      ["kbp_Latn"] = "Kabiyè",
      ["kea_Latn"] = "Kabuverdianu",
      ["khm_Khmr"] = "Khmer",
      ["kik_Latn"] = "Kikuyu",
      ["kin_Latn"] = "Kinyarwanda",
      ["kir_Cyrl"] = "Kyrgyz",
      ["kmb_Latn"] = "Kimbundu",
      ["kmr_Latn"] = "Northern Kurdish",
      ["kon_Latn"] = "Kikongo",
      ["kor_Hang"] = "Korean",
      ["lao_Laoo"] = "Lao",
      ["lij_Latn"] = "Ligurian",
      ["lim_Latn"] = "Limburgish",
      ["lin_Latn"] = "Lingala",
      ["lit_Latn"] = "Lithuanian",
      ["lmo_Latn"] = "Lombard",
      ["ltg_Latn"] = "Latgalian",
      ["ltz_Latn"] = "Luxembourgish",
      ["lua_Latn"] = "Luba-Kasai",
      ["lug_Latn"] = "Ganda",
      ["luo_Latn"] = "Luo",
      ["lus_Latn"] = "Mizo",
      ["lvs_Latn"] = "Standard Latvian",
      ["mag_Deva"] = "Magahi",
      ["mai_Deva"] = "Maithili",
      ["mal_Mlym"] = "Malayalam",
      ["mar_Deva"] = "Marathi",
      ["min_Arab"] = "Minangkabau (Arabic script)",
      ["min_Latn"] = "Minangkabau (Latin script)",
      ["mkd_Cyrl"] = "Macedonian",
      ["plt_Latn"] = "Plateau Malagasy",
      ["mlt_Latn"] = "Maltese",
      ["mni_Beng"] = "Meitei (Bengali script)",
      ["khk_Cyrl"] = "Halh Mongolian",
      ["mos_Latn"] = "Mossi",
      ["mri_Latn"] = "Maori",
      ["mya_Mymr"] = "Burmese",
      ["nld_Latn"] = "Dutch",
      ["nno_Latn"] = "Norwegian Nynorsk",
      ["nob_Latn"] = "Norwegian Bokmål",
      ["npi_Deva"] = "Nepali",
      ["nso_Latn"] = "Northern Sotho",
      ["nus_Latn"] = "Nuer",
      ["nya_Latn"] = "Nyanja",
      ["oci_Latn"] = "Occitan",
      ["gaz_Latn"] = "West Central Oromo",
      ["ory_Orya"] = "Odia",
      ["pag_Latn"] = "Pangasinan",
      ["pan_Guru"] = "Eastern Panjabi",
      ["pap_Latn"] = "Papiamento",
      ["pes_Arab"] = "Western Persian",
      ["pol_Latn"] = "Polish",
      ["por_Latn"] = "Portuguese",
      ["prs_Arab"] = "Dari",
      ["pbt_Arab"] = "Southern Pashto",
      ["quy_Latn"] = "Ayacucho Quechua",
      ["ron_Latn"] = "Romanian",
      ["run_Latn"] = "Rundi",
      ["rus_Cyrl"] = "Russian",
      ["sag_Latn"] = "Sango",
      ["san_Deva"] = "Sanskrit",
      ["sat_Olck"] = "Santali",
      ["scn_Latn"] = "Sicilian",
      ["shn_Mymr"] = "Shan",
      ["sin_Sinh"] = "Sinhala",
      ["slk_Latn"] = "Slovak",
      ["slv_Latn"] = "Slovenian",
      ["smo_Latn"] = "Samoan",
      ["sna_Latn"] = "Shona",
      ["snd_Arab"] = "Sindhi",
      ["som_Latn"] = "Somali",
      ["sot_Latn"] = "Southern Sotho",
      ["spa_Latn"] = "Spanish",
      ["als_Latn"] = "Tosk Albanian",
      ["srd_Latn"] = "Sardinian",
      ["srp_Cyrl"] = "Serbian",
      ["ssw_Latn"] = "Swati",
      ["sun_Latn"] = "Sundanese",
      ["swe_Latn"] = "Swedish",
      ["swh_Latn"] = "Swahili",
      ["szl_Latn"] = "Silesian",
      ["tam_Taml"] = "Tamil",
      ["tat_Cyrl"] = "Tatar",
      ["tel_Telu"] = "Telugu",
      ["tgk_Cyrl"] = "Tajik",
      ["tgl_Latn"] = "Tagalog",
      ["tha_Thai"] = "Thai",
      ["tir_Ethi"] = "Tigrinya",
      ["taq_Latn"] = "Tamasheq (Latin script)",
      ["taq_Tfng"] = "Tamasheq (Tifinagh script)",
      ["tpi_Latn"] = "Tok Pisin",
      ["tsn_Latn"] = "Tswana",
      ["tso_Latn"] = "Tsonga",
      ["tuk_Latn"] = "Turkmen",
      ["tum_Latn"] = "Tumbuka",
      ["tur_Latn"] = "Turkish",
      ["twi_Latn"] = "Twi",
      ["tzm_Tfng"] = "Central Atlas Tamazight",
      ["uig_Arab"] = "Uyghur",
      ["ukr_Cyrl"] = "Ukrainian",
      ["umb_Latn"] = "Umbundu",
      ["urd_Arab"] = "Urdu",
      ["uzn_Latn"] = "Northern Uzbek",
      ["vec_Latn"] = "Venetian",
      ["vie_Latn"] = "Vietnamese",
      ["war_Latn"] = "Waray",
      ["wol_Latn"] = "Wolof",
      ["xho_Latn"] = "Xhosa",
      ["ydd_Hebr"] = "Eastern Yiddish",
      ["yor_Latn"] = "Yoruba",
      ["yue_Hant"] = "Yue Chinese",
      ["zho_Hans"] = "Chinese (Simplified)",
      ["zho_Hant"] = "Chinese (Traditional)",
      ["zsm_Latn"] = "Standard Malay",
      ["zul_Latn"] = "Zulu"
   };

}