using AIHappey.Core.Models;

namespace AIHappey.Core.Providers.Segmind;

public partial class SegmindProvider
{
  public async Task<IEnumerable<Model>> ListModels(CancellationToken cancellationToken = default)
  {
    if (string.IsNullOrWhiteSpace(_keyResolver.Resolve(GetIdentifier())))
      return await Task.FromResult<IEnumerable<Model>>([]);


    ApplyAuthHeader();

    foreach (var model in SegmindModels)
      model.Type = "image";

    return SegmindModels;
  }

  public static readonly IReadOnlyList<Model> SegmindModels =
[
    new() { Id = "segmind/grok-2-vision", Name = "grok-2-vision" },
    new() { Id = "segmind/grok-2", Name = "grok-2" },
    new() { Id = "segmind/image-upscale", Name = "image-upscale" },
    new() { Id = "segmind/z-image-turbo", Name = "z-image-turbo" },
    new() { Id = "segmind/ace-step-music", Name = "ace-step-music" },
    new() { Id = "segmind/stable-diffusion-xl-1.0", Name = "stable-diffusion-xl-1.0" },
    new() { Id = "segmind/stable-diffusion-xl-0.9", Name = "stable-diffusion-xl-0.9" },
    new() { Id = "segmind/stable-diffusion-inpainting", Name = "stable-diffusion-inpainting" },
    new() { Id = "segmind/stable-diffusion-img2img", Name = "stable-diffusion-img2img" },
    new() { Id = "segmind/stable-diffusion-3.5-turbo-text-to-image", Name = "stable-diffusion-3.5-turbo-text-to-image" },
    new() { Id = "segmind/stable-diffusion-3.5-large-text-to-image", Name = "stable-diffusion-3.5-large-text-to-image" },
    new() { Id = "segmind/stable-diffusion-3-medium-text-to-image", Name = "stable-diffusion-3-medium-text-to-image" },
    new() { Id = "segmind/stable-diffusion-2.1", Name = "stable-diffusion-2.1" },
    new() { Id = "segmind/sdxl-inpaint", Name = "sdxl-inpaint" },
    new() { Id = "segmind/sd3-medium-tile-controlnet", Name = "sd3-medium-tile-controlnet" },
    new() { Id = "segmind/sd3-medium-pose-controlnet", Name = "sd3-medium-pose-controlnet" },
    new() { Id = "segmind/sd3-medium-canny-controlnet", Name = "sd3-medium-canny-controlnet" },

    new() { Id = "segmind/zavychroma-sdxl", Name = "zavychroma-sdxl" },
    new() { Id = "segmind/word2img", Name = "word2img" },
    new() { Id = "segmind/wildcard-lightning-sdxl", Name = "wildcard-lightning-sdxl" },
    new() { Id = "segmind/try-on-diffusion", Name = "try-on-diffusion" },
    new() { Id = "segmind/transparent-background-maker", Name = "transparent-background-maker" },
    new() { Id = "segmind/tiny-sd-portrait", Name = "tiny-sd-portrait" },
    new() { Id = "segmind/tiny-sd", Name = "tiny-sd" },
    new() { Id = "segmind/text-overlay", Name = "text-overlay" },
    new() { Id = "segmind/supir-photo-realistic-restoration", Name = "supir-photo-realistic-restoration" },
    new() { Id = "segmind/ssd-img2img", Name = "ssd-img2img" },
    new() { Id = "segmind/ssd-depth", Name = "ssd-depth" },
    new() { Id = "segmind/ssd-canny", Name = "ssd-canny" },
    new() { Id = "segmind/ssd-1b", Name = "ssd-1b" },
    new() { Id = "segmind/small-sd", Name = "small-sd" },
    new() { Id = "segmind/skin-contrast-upscaler", Name = "skin-contrast-upscaler" },
    new() { Id = "segmind/segswap-v0.1", Name = "segswap-v0.1" },
    new() { Id = "segmind/segmind-vegart", Name = "segmind-vegart" },
    new() { Id = "segmind/segmind-vega", Name = "segmind-vega" },
    new() { Id = "segmind/segfit-v1.3", Name = "segfit-v1.3" },
    new() { Id = "segmind/segfit-v1.2", Name = "segfit-v1.2" },
    new() { Id = "segmind/segfit-v1.1", Name = "segfit-v1.1" },
    new() { Id = "segmind/sdxl-openpose", Name = "sdxl-openpose" },
    new() { Id = "segmind/sd-outpainting", Name = "sd-outpainting" },
    new() { Id = "segmind/scifi", Name = "scifi" },
    new() { Id = "segmind/scenecraft-v0.1", Name = "scenecraft-v0.1" },
    new() { Id = "segmind/samaritan-lightning-sdxl", Name = "samaritan-lightning-sdxl" },
    new() { Id = "segmind/samaritan-3d-xl", Name = "samaritan-3d-xl" },
    new() { Id = "segmind/samaritan", Name = "samaritan" },
    new() { Id = "segmind/rpg", Name = "rpg" },
    new() { Id = "segmind/revanimated", Name = "revanimated" },
    new() { Id = "segmind/relighting-v2", Name = "relighting-v2" },
    new() { Id = "segmind/relighting", Name = "relighting" },
    new() { Id = "segmind/reliberate", Name = "reliberate" },
    new() { Id = "segmind/realvis-sdxl", Name = "realvis-sdxl" },
    new() { Id = "segmind/realvis-lightning-sdxl", Name = "realvis-lightning-sdxl" },
    new() { Id = "segmind/realistic-vision", Name = "realistic-vision" },
    new() { Id = "segmind/realism-lightning-sdxl", Name = "realism-lightning-sdxl" },
    new() { Id = "segmind/realdream-pony-v9", Name = "realdream-pony-v9" },
    new() { Id = "segmind/realdream-lightning", Name = "realdream-lightning" },
    new() { Id = "segmind/rcnz-cartoon", Name = "rcnz-cartoon" },
    new() { Id = "segmind/qr-generator", Name = "qr-generator" },
    new() { Id = "segmind/protovision-lightning-sdxl", Name = "protovision-lightning-sdxl" },
    new() { Id = "segmind/profile-photo-style-transfer", Name = "profile-photo-style-transfer" },
    new() { Id = "segmind/paragon", Name = "paragon" },
    new() { Id = "segmind/omini-control", Name = "omini-control" },
    new() { Id = "segmind/nomos-image-upscaler-4k", Name = "nomos-image-upscaler-4k" },
    new() { Id = "segmind/nightvis-lightning-sdxl", Name = "nightvis-lightning-sdxl" },
    new() { Id = "segmind/material-transfer", Name = "material-transfer" },
    new() { Id = "segmind/manmarumix", Name = "manmarumix" },
    new() { Id = "segmind/majicmix", Name = "majicmix" },
    new() { Id = "segmind/magic-eraser", Name = "magic-eraser" },
    new() { Id = "segmind/kandinsky-2.1", Name = "kandinsky-2.1" },
    new() { Id = "segmind/juggernaut-pro-flux", Name = "juggernaut-pro-flux" },
    new() { Id = "segmind/juggernaut-lightning-sdxl", Name = "juggernaut-lightning-sdxl" },
    new() { Id = "segmind/juggernaut-lightning-flux", Name = "juggernaut-lightning-flux" },
    new() { Id = "segmind/juggernaut-final", Name = "juggernaut-final" },
    new() { Id = "segmind/ipadapter-style-transfer", Name = "ipadapter-style-transfer" },
    new() { Id = "segmind/ip-adapter-openpose-xl", Name = "ip-adapter-openpose-xl" },
    new() { Id = "segmind/ip-adapter-depth-xl", Name = "ip-adapter-depth-xl" },
    new() { Id = "segmind/ip-adapter-canny-xl", Name = "ip-adapter-canny-xl" },
    new() { Id = "segmind/instantid", Name = "instantid" },
    new() { Id = "segmind/insta-depth", Name = "insta-depth" },
    new() { Id = "segmind/infinite-you", Name = "infinite-you" },
    new() { Id = "segmind/image-superimpose-v2", Name = "image-superimpose-v2" },
    new() { Id = "segmind/illusion-diffusion-hq", Name = "illusion-diffusion-hq" },
    new() { Id = "segmind/idm-vton", Name = "idm-vton" },
    new() { Id = "segmind/fruit-fusion", Name = "fruit-fusion" },
    new() { Id = "segmind/fooocus-outpainting", Name = "fooocus-outpainting" },
    new() { Id = "segmind/fooocus-inpainting", Name = "fooocus-inpainting" },
    new() { Id = "segmind/fooocus", Name = "fooocus" },
    new() { Id = "segmind/font-sheet-generator", Name = "font-sheet-generator" },
    new() { Id = "segmind/flat-2d", Name = "flat-2d" },
    new() { Id = "segmind/fast-flux-1-schnell", Name = "fast-flux-1-schnell" },
    new() { Id = "segmind/fantassified-icons", Name = "fantassified-icons" },
    new() { Id = "segmind/faceswap-v5", Name = "faceswap-v5" },
    new() { Id = "segmind/faceswap-v4", Name = "faceswap-v4" },
    new() { Id = "segmind/faceswap-v3-multifaceswap", Name = "faceswap-v3-multifaceswap" },
    new() { Id = "segmind/faceswap-v3", Name = "faceswap-v3" },
    new() { Id = "segmind/faceswap-v2", Name = "faceswap-v2" },
    new() { Id = "segmind/faceswap-comic-v1", Name = "faceswap-comic-v1" },
    new() { Id = "segmind/faceswap", Name = "faceswap" },
    new() { Id = "segmind/face-to-sticker", Name = "face-to-sticker" },
    new() { Id = "segmind/face-to-many", Name = "face-to-many" },
    new() { Id = "segmind/face-detailer", Name = "face-detailer" },
    new() { Id = "segmind/expression-editor", Name = "expression-editor" },
    new() { Id = "segmind/esrgan", Name = "esrgan" },
    new() { Id = "segmind/epic-realism", Name = "epic-realism" },
    new() { Id = "segmind/edge-of-realism", Name = "edge-of-realism" },
    new() { Id = "segmind/dynavis-lightning-sdxl", Name = "dynavis-lightning-sdxl" },
    new() { Id = "segmind/dvarch", Name = "dvarch" },
    new() { Id = "segmind/dreamshaper-sdxl", Name = "dreamshaper-sdxl" },
    new() { Id = "segmind/dreamshaper-lightning-sdxl", Name = "dreamshaper-lightning-sdxl" },
    new() { Id = "segmind/dream-shaper", Name = "dream-shaper" },
    new() { Id = "segmind/deep-spaced-diffusion", Name = "deep-spaced-diffusion" },
    new() { Id = "segmind/cyber-realistic", Name = "cyber-realistic" },
    new() { Id = "segmind/cute-rich-style", Name = "cute-rich-style" },
    new() { Id = "segmind/copax-timeless-sdxl", Name = "copax-timeless-sdxl" },
    new() { Id = "segmind/controlnet-soft-edge", Name = "controlnet-soft-edge" },
    new() { Id = "segmind/controlnet-scribble", Name = "controlnet-scribble" },
    new() { Id = "segmind/controlnet-openpose", Name = "controlnet-openpose" },
    new() { Id = "segmind/controlnet-depth", Name = "controlnet-depth" },
    new() { Id = "segmind/controlnet-canny", Name = "controlnet-canny" },
    new() { Id = "segmind/consistent-character-with-pose", Name = "consistent-character-with-pose" },
    new() { Id = "segmind/consistent-character-v1", Name = "consistent-character-v1" },
    new() { Id = "segmind/consistent-character-ai-neolemon-v3", Name = "consistent-character-ai-neolemon-v3" },
    new() { Id = "segmind/consistent-character-ai-neolemon-v2", Name = "consistent-character-ai-neolemon-v2" },
    new() { Id = "segmind/consistent-character", Name = "consistent-character" },
    new() { Id = "segmind/colossus-lightning-sdxl", Name = "colossus-lightning-sdxl" },
    new() { Id = "segmind/colorful", Name = "colorful" },
    new() { Id = "segmind/codeformer", Name = "codeformer" },
    new() { Id = "segmind/clarity-upscaler", Name = "clarity-upscaler" },
    new() { Id = "segmind/caricature-style", Name = "caricature-style" },
    new() { Id = "segmind/beyond-outpaint", Name = "beyond-outpaint" },
    new() { Id = "segmind/background-replace", Name = "background-replace" },
    new() { Id = "segmind/background-removal", Name = "background-removal" },
    new() { Id = "segmind/all-in-one-pixe", Name = "all-in-one-pixe" },
    new() { Id = "segmind/ai-product-photography", Name = "ai-product-photography" },
    new() { Id = "segmind/ai-product-photo-editor", Name = "ai-product-photo-editor" },
    new() { Id = "segmind/526mix", Name = "526mix" }
];

}
